### ISSUE TITLE
Colcon Build Failing

### ISSUE THREAD

**Issue by daedalus-ode** [osrf/rmw_zenoh#144] opened 2024-03-30 08:51 UTC
## Overview :  
After cloning the git repository into my system and  trying to build the package using colcon build. It failed by throwing the following error.  
## Command :  
ubundadu@USER:~/ws_rmw_zenoh$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release  
## Output :   

......
Compiling zenoh-ext v0.11.0-dev (https://github.com/eclipse-zenoh/zenoh.git?branch=main#4537dc26)
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
  --> /home/ubundadu/ws_rmw_zenoh/build/zenoh_c_vendor/zenoh_c_vendor-prefix/src/zenoh_c_vendor/src/lib.rs:82:26
   |
82 |                 unsafe { std::mem::transmute::<$src_type, $dst_type>(self) }
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
  ::: /home/ubundadu/ws_rmw_zenoh/build/zenoh_c_vendor/zenoh_c_vendor-prefix/src/zenoh_c_vendor/src/get.rs:63:1
   |
63 | impl_guarded_transmute!(ReplyInner, z_owned_reply_t);
   | ---------------------------------------------------- in this macro invocation
   |
   = note: source type: `Option<zenoh::query::Reply>` (1920 bits)
   = note: target type: `get::z_owned_reply_t` (1792 bits)
   = note: this error originates in the macro `impl_guarded_transmute` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0512`.
error: could not compile `zenoh-c` (lib) due to 1 previous error
gmake[5]: *** [CMakeFiles/cargo.dir/build.make:111: release/target/release/libzenohc.so] Error 101
gmake[4]: *** [CMakeFiles/Makefile2:180: CMakeFiles/cargo.dir/all] Error 2
gmake[3]: *** [Makefile:146: all] Error 2
gmake[2]: *** [CMakeFiles/zenoh_c_vendor.dir/build.make:85: zenoh_c_vendor-prefix/src/zenoh_c_vendor-stamp/zenoh_c_vendor-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/zenoh_c_vendor.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

Failed   <<< zenoh_c_vendor [1min 55s, exited with code 2]

Summary: 0 packages finished [1min 55s]
  1 package failed: zenoh_c_vendor
  1 package had stderr output: zenoh_c_vendor
  1 package not processed  

### rustc --version  
rustc 1.77.0 (aedd173a2 2024-03-17)  
### cargo --version  
cargo 1.77.0 (3fe68eabf 2024-02-29)  
### System  
wsl2 - Ubuntu-22.04 (LTS)

**Comment by Yadunund** [comment] 2024-03-30 09:41
We're currently pinning the version of cargo to be used at `1.75.0`. See https://github.com/ros2/rmw_zenoh/pull/136 for more details. I'll close this ticket now as it is a duplicate of https://github.com/ros2/rmw_zenoh/issues/138 but feel free to reopen if you feel otherwise.

**Closed as completed by Yadunund** 2024-03-30 09:41 UTC
