### ISSUE TITLE
Investigate potential bug in rmw API 

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmw_zenoh#74] opened 2023-12-02 00:30 UTC
`rmw_shutdown()` is invoked by `rcl` before `rmw_destroy_node()`. See https://github.com/ros2/rmw_zenoh/blob/85698981dafe966f18b83a525875436c8443476a/rmw_zenoh_cpp/src/rmw_init.cpp#L372-L375

**Comment by clalancette** [comment] 2024-01-23 15:55
This is by design; see #92.  Closing this one out.

**Closed as completed by clalancette** 2024-01-23 15:55 UTC
